### ISSUE TITLE
Exist not found!

### ISSUE THREAD

**Issue by Magicperf** [rwitzel/CouchRepository#1]
Description:

An attempt was made to call the method com.github.rwitzel.couchrepository.api.CouchDbCrudRepository.exists(Ljava/io/Serializable;)Z but it does not exist. Its class, com.github.rwitzel.couchrepository.api.CouchDbCrudRepository, is available

**Comment by rwitzel** [comment]
Hi Magic! How did you get this error?

**Comment by Magicperf** [comment]
I set it up from scratch using Spring Boot 2.1. Just copied your code with my own logic and when trying to run in tomcat 9, i get that error during initialization

**Comment by rwitzel** [comment]
Could you tell me the Spring Data JPA version you are using?

**Comment by mueller-jens** [comment]
We are also use actual version of spring boot (2.0.8.RELEASE) this provides spring-data-comons: 2.0.13.Release.
hiere the api has changed. The method signature has changed to boolean existsById(ID id);

**Comment by mueller-jens** [comment]
We are also use actual version of spring boot (2.0.8.RELEASE) this provides spring-data-comons: 2.0.13.Release.
 here the api has changed. The method signature has changed to boolean existsById(ID id). There are also changes in the find method signatures

**Comment by chrisinmtown** [comment]
Spring boot release version is up to 2.1.6.RELEASE, I guess the "exists-method-not-found" problem would affect it equally, is there any news here?

**Comment by mueller-jens** [comment]
@chrisinmtown it is because the segnature of some methoda has changed in spring-jpa-data i have changed the it and requested a pull request https://github.com/rwitzel/CouchRepository/pull/2 by rwitzel. That is in wait status since some month.

**Comment by rwitzel** [comment]
Thank you for the reminder! Please note my comment at the PR.

**Comment by rwitzel** [comment]
Fixed via #2 , thanks to @mueller-jens
